apiVersion: v2
name: expense-iq-backend
description: "ExpenseIQ Backend API"ss
type: application
version: 1.0.0
appVersion: "1.13.0-SNAPSHOT"
home: "https://github.com/ikusen/expense-platform"
icon: "https://raw.githubusercontent.com/ikusen/expense-platform/main/icon.png"